# Generated by Django 4.0.3 on 2022-03-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delayed_orders',
            old_name='customer_time',
            new_name='current_time',
        ),
    ]
